volumes:
  jenkins-data:
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jnks
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root # sรณ funcionou com root no meu computador com Windows + WSL2 + Docker Desktop